[book]
title = "Hylang"
description = "A C#-inspired systems language for Aura OS and general x64 systems."
authors = ["Aurora Softwares"]
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/Aurora-Softwares/Hylang-Compiler"
edit-url-template = "https://github.com/Aurora-Softwares/Hylang-Docs/edit/main/{path}"
no-section-label = false
additional-css = ["theme/custom.css"]
additional-js = ["theme/custom.js"]
